import json
import os

# Point to ../data relative to backend/
DATA_FOLDER = os.path.join(os.path.dirname(__file__), "..", "data")

FILES = [
    "africa_priority_rules.json",
    "who_essential_medicines_rules.json",
    "drugbank_interactions.json",
    "openfda_rules.json"   # regenerated by fetch_openfda.py
]

import requests

def sync_rules(ruleset):
    url = "http://127.0.0.1:8000/api/sync"
    try:
        resp = requests.get(url, timeout=10)
        resp.raise_for_status()
        demo_data = resp.json()
        if "rules" in demo_data:
            ruleset["rules"].extend(demo_data["rules"])
        if "metadata" in demo_data and "source" in demo_data["metadata"]:
            ruleset["metadata"]["sources"].append(demo_data["metadata"]["source"])
        print("✅ Demo sync successful — merged rules")
    except Exception as e:
        print(f"⚠️ Sync failed: {e}")


def load_rules():
    """Load and merge rules from all JSON datasets."""
    merged_rules = []
    metadata_sources = []

    for filename in FILES:
        path = os.path.join(DATA_FOLDER, filename)
        if not os.path.exists(path):
            print(f"⚠️ File not found: {filename}")
            continue
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
            if "rules" in data:
                merged_rules.extend(data["rules"])
            if "metadata" in data and "source" in data["metadata"]:
                metadata_sources.append(data["metadata"]["source"])

    merged_output = {
        "metadata": {
            "sources": metadata_sources,
            "last_updated": "2026-06-05",
            "notes": "Merged rules engine dataset for OCML-DI"
        },
        "rules": merged_rules
    }
    return merged_output

def evaluate_interaction(drug, condition_or_conflict, ruleset):
    """Evaluate a drug interaction against merged rules."""
    results = []
    for rule in ruleset["rules"]:
        if rule["drug"].lower() == drug.lower() and rule["conflict_with"].lower() == condition_or_conflict.lower():
            results.append(rule)
    return results

if __name__ == "__main__":
    ruleset = load_rules()
    print(f"✅ Loaded {len(ruleset['rules'])} rules from merged datasets")

    # Example evaluation
    test_results = evaluate_interaction("Efavirenz", "Rifampicin", ruleset)
    if test_results:
        print("🔎 Interaction found:")
        for r in test_results:
            print(f"- {r['drug']} + {r['conflict_with']} → {r['risk_level']} risk: {r['outcome']}")
            print(f"  Recommendation: {r['recommendation']}")
    else:
        print("No interaction found for test case.")